title: Holger Graef
logo: /assets/img/logo.jpg
description: PhD student in high frequency electronics with nanostructured devices based on encapsulated graphene
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
